- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print name
    ansible.builtin.debug
      msg: "Hello {{ itme }}" #item is reserved
    loop:
    - Ramesh
    - Suresh
    - Raheem 
    - jhon

    