- name: install and start nginx
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    #ansible.builtin.service: # this is legacy 
    ansible.builtin.systemd:  # use this now i gooogled
      name: nginx
      state: started
      enable: yes

  # - name: start nginx
  # ansible.builtin.systemd:
  #  name: nginx
  #  state: started
  # enabled: yes

