- name: play level variables
  hosts: local
  collections: local # Ansible is connecting to local
  vars:
    COURSE: DevOps with AWS
    DURATION: 10HRS
    Trainer: Raman 
  tasks:
  - name: print the couse info
    vars:
      COURSE: Ansible
    ansible.builtin.debug:
      msg: "Couse Name is: {{ COURSE }}, DURATION: {{ DURATION }}, Trainer: {{ Trainer }}"
