- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
<<<<<<< HEAD
    prompt: What is your username?
=======
    prompt: what is your username?
>>>>>>> 8fbddce (files3)
    private: false
  - name: password
    prompt: What is your password?
    private: true
  tasks:
  - name: print credentials
    ansible.builtin.debug:
<<<<<<< HEAD
      msg: "Hello, Username is: {{ username }}, Password is: {{ password }}"
      
=======
      meg: "Hello, username is: {{ username }}, passsword is: {{ passsword }}"

- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: What is your username?
    private: false
  - name: password
    prompt: What is your password?
    private: true
  tasks:
  - name: print credentials
    ansible.builtin.debug:
      msg: "Hello, Username is: {{ username }}, Password is: {{ password }}"
>>>>>>> 8fbddce (files3)
