- name: variables from files
  hosts: local
  collection: local
  tasks:
  - name: print cousre info
    ansible.builtin.debug:
      msg: "Couse Name is: {{ COURSE }}, Duration: {{ DURATION}}, Trainer:  {{ TRAINER }}"
